require('dotenv').config();
const express = require('express');
const cors = require('cors');
const pool = require('./db/postgres');
const redis = require('./db/redis');
const integrationsRouter = require('./routes/integrations');
const webhooks99foodRouter = require('./routes/webhooks99food');
const webhooksifoodRouter = require('./routes/webhooksifood');
const dashboardRouter = require('./routes/dashboard');
const authRouter = require('./routes/auth');
const automationsRouter = require('./routes/automations');
const restaurantsRouter = require('./routes/restaurants');
const reportsRouter = require('./routes/reports');
const settingsRouter = require('./routes/settings');
const adminRouter = require('./routes/admin');
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors());
app.use(express.json());
app.get('/health', async (req, res) => {
  let dbStatus = 'erro';
  let redisStatus = 'erro';
  try { await pool.query('SELECT 1'); dbStatus = 'ok'; } catch (err) { console.error('[health] postgres:', err.message); }
  try { await redis.ping(); redisStatus = 'ok'; } catch (err) { console.error('[health] redis:', err.message); }
  res.json({ status: 'ok', postgres: dbStatus, redis: redisStatus, timestamp: new Date().toISOString() });
});
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/webhooks/99food', webhooks99foodRouter);
app.use('/api/v1/webhooks/ifood', webhooksifoodRouter);
app.use('/api/v1/integrations', integrationsRouter);
app.use('/api/v1/orders/99food', webhooks99foodRouter);
app.use('/api/v1/orders/ifood', webhooksifoodRouter);
app.use('/api/v1/dashboard', dashboardRouter);
app.use('/api/v1/automations', automationsRouter);
app.use('/api/v1/restaurants', restaurantsRouter);
app.use('/api/v1/reports', reportsRouter);
app.use('/api/v1/settings', settingsRouter);
app.use('/api/v1/admin', adminRouter);
app.use((req, res) => { res.status(404).json({ error: 'Rota não encontrada' }); });
app.listen(PORT, () => { console.log(`Delivery Auto Pro backend rodando na porta ${PORT}`); });
